GRLIB_arsenal_weapons = [

    // Vanilla Rifles
    "sgun_HunterShotgun_01_F",
    "sgun_HunterShotgun_01_sawedoff_F",

    // Vanilla Pistols
    "hgun_ACPC2_F",
	"hgun_P07_F",
	"hgun_P07_blk_F",
	"hgun_P07_khk_F",
	"hgun_Pistol_01_F",
	"hgun_Pistol_Signal_F",
	"hgun_Pistol_heavy_01_F",
	"hgun_Pistol_heavy_01_green_F",
	"hgun_Pistol_heavy_02_F",
	"hgun_Rook40_F",
    
    // ACE Pistols
    "ACE_Flashlight_Maglite_ML300L",
    "ACE_VMH3",
    "ACE_VMM3",
];

GRLIB_arsenal_magazines = [

    // Vanilla Ammo
    "10Rnd_9x21_Mag",
	"11Rnd_45ACP_Mag",
	"16Rnd_9x21_Mag",
	"16Rnd_9x21_green_Mag",
	"16Rnd_9x21_red_Mag",
	"16Rnd_9x21_yellow_Mag",
	"2Rnd_12Gauge_Pellets",
	"2Rnd_12Gauge_Slug",
	"6Rnd_RedSignal_F",
	"hgun_ACPC2_F",
	"hgun_Pistol_Signal_F",
	"hgun_Pistol_heavy_02_F",

	// Vanilla Grenades
	"Chemlight_blue",
	"Chemlight_green",
	"Chemlight_red",
	"Chemlight_yellow",
	"SmokeShell",
	"SmokeShellBlue",
	"SmokeShellGreen",
	"SmokeShellOrange",
	"SmokeShellPurple",
	"SmokeShellRed",
	"SmokeShellYellow",

	// Vanilla Explosives
	"APERSBoundingMine_Range_Mag",
	"APERSMineDispenser_Mag",
	"APERSMine_Range_Mag",
	"APERSTripMine_Wire_Mag",
	"ATMine_Range_Mag",
	"ClaymoreDirectionalMine_Remote_Mag",
	"DemoCharge_Remote_Mag",
	"IEDLandSmall_Remote_Mag",
	"IEDUrbanSmall_Remote_Mag",
	"SLAMDirectionalMine_Wire_Mag",
	"SatchelCharge_Remote_Mag",
	"TrainingMine_Mag",

    // ACE Ammo
	"ACE_2Rnd_12Gauge_Pellets_No0_Buck",
	"ACE_2Rnd_12Gauge_Pellets_No1_Buck",
	"ACE_2Rnd_12Gauge_Pellets_No2_Buck",
	"ACE_2Rnd_12Gauge_Pellets_No3_Buck",
	"ACE_2Rnd_12Gauge_Pellets_No4_Bird",
	"ACE_2Rnd_12Gauge_Pellets_No4_Buck",

	// ACE Grenades
	"ACE_Chemlight_HiBlue",
	"ACE_Chemlight_HiGreen",
	"ACE_Chemlight_HiRed",
	"ACE_Chemlight_HiWhite",
	"ACE_Chemlight_HiYellow",
	"ACE_Chemlight_IR",
	"ACE_Chemlight_Orange",
	"ACE_Chemlight_UltraHiOrange",
	"ACE_Chemlight_White",
	"ACE_HandFlare_Green",
	"ACE_HandFlare_Red",
	"ACE_HandFlare_White",
	"ACE_HandFlare_Yellow",
	"ACE_M14",
	"ACE_M84",

	// ACE Explosives
	"ACE_FlareTripMine_Mag",
];

GRLIB_arsenal_items = [

    // Vanilla Helmets
    "H_Bandanna_blu",
	"H_Bandanna_camo",
	"H_Bandanna_cbr",
	"H_Bandanna_gry",
	"H_Bandanna_khk",
	"H_Bandanna_khk_hs",
	"H_Bandanna_mcamo",
	"H_Bandanna_sand",
	"H_Bandanna_sgg",
	"H_Bandanna_surfer",
	"H_Bandanna_surfer_blk",
	"H_Bandanna_surfer_grn",
	"H_Booniehat_dgtl",
	"H_Booniehat_eaf",
	"H_Booniehat_khk",
	"H_Booniehat_khk_hs",
	"H_Booniehat_mcamo",
	"H_Booniehat_mgrn",
	"H_Booniehat_oli",
	"H_Booniehat_taiga",
	"H_Booniehat_tan",
	"H_Booniehat_tna_F",
	"H_Booniehat_wdl",
	"H_Cap_Black_IDAP_F",
	"H_Cap_Lyfe",
	"H_Cap_MaldenTours",
	"H_Cap_Orange_IDAP_F",
	"H_Cap_White_IDAP_F",
	"H_Cap_blk",
	"H_Cap_blk_CMMG",
	"H_Cap_blk_ION",
	"H_Cap_blk_Raven",
	"H_Cap_blu",
	"H_Cap_brn_SPECOPS",
	"H_Cap_grn",
	"H_Cap_grn_BI",
	"H_Cap_headphones",
	"H_Cap_khaki_specops_UK",
	"H_Cap_marshal",
	"H_Cap_oli",
	"H_Cap_oli_hs",
	"H_Cap_red",
	"H_Cap_surfer",
	"H_Cap_tan",
	"H_Cap_tan_specops_US",
	"H_Cap_usblack",
	"H_Construction_basic_yellow_F",
	"H_Construction_earprot_yellow_F",
	"H_Construction_headset_yellow_F",
	"H_EarProtectors_black_F",
	"H_Hat_Safari_olive_F",
	"H_Hat_Safari_sand_F",
	"H_Hat_Tinfoil_F",
	"H_Hat_blue",
	"H_Hat_brown",
	"H_Hat_camo",
	"H_Hat_checker",
	"H_Hat_grey",
	"H_Hat_tan",
	"H_HeadBandage_bloody_F",
	"H_HeadBandage_clean_F",
	"H_HeadBandage_stained_F",
	"H_HeadSet_black_F",
	"H_Helmet_Skate",
	"H_MilCap_blue",
	"H_MilCap_dgtl",
	"H_MilCap_eaf",
	"H_MilCap_ghex_F",
	"H_MilCap_grn",
	"H_MilCap_gry",
	"H_MilCap_mcamo",
	"H_MilCap_ocamo",
	"H_MilCap_taiga",
	"H_MilCap_tna_F",
	"H_MilCap_wdl",
	"H_ShemagOpen_khk",
	"H_ShemagOpen_tan",
	"H_Shemag_olive",
	"H_Shemag_olive_hs",
	"H_StrawHat",
	"H_StrawHat_dark",
	"H_Watchcap_blk",
	"H_Watchcap_camo",
	"H_Watchcap_cbr",
	"H_Watchcap_khk",
	"H_WirelessEarpiece_F",

    // Vanilla Uniforms
    "U_BG_Guerilla1_1",
	"U_BG_Guerilla2_1",
	"U_BG_Guerilla2_2",
	"U_BG_Guerilla2_3",
	"U_BG_Guerilla3_1",
	"U_BG_Guerrilla_6_1",
	"U_B_GEN_Commander_F",
	"U_B_GEN_Soldier_F",
	"U_B_Wetsuit",
	"U_C_ArtTShirt_01_v1_F",
	"U_C_ArtTShirt_01_v2_F",
	"U_C_ArtTShirt_01_v3_F",
	"U_C_ArtTShirt_01_v4_F",
	"U_C_ArtTShirt_01_v5_F",
	"U_C_ArtTShirt_01_v6_F",
	"U_C_CBRN_Suit_01_Blue_F",
	"U_C_CBRN_Suit_01_White_F",
	"U_C_ConstructionCoverall_Black_F",
	"U_C_ConstructionCoverall_Blue_F",
	"U_C_ConstructionCoverall_Red_F",
	"U_C_ConstructionCoverall_Vrana_F",
	"U_C_E_LooterJacket_01_F",
	"U_C_FormalSuit_01_black_F",
	"U_C_FormalSuit_01_blue_F",
	"U_C_FormalSuit_01_gray_F",
	"U_C_FormalSuit_01_khaki_F",
	"U_C_FormalSuit_01_tshirt_black_F",
	"U_C_FormalSuit_01_tshirt_gray_F",
	"U_C_HunterBody_grn",
	"U_C_IDAP_Man_Jeans_F",
	"U_C_IDAP_Man_TeeShorts_F",
	"U_C_IDAP_Man_Tee_F",
	"U_C_IDAP_Man_cargo_F",
	"U_C_IDAP_Man_casual_F",
	"U_C_IDAP_Man_shorts_F",
	"U_C_Journalist",
	"U_C_Man_casual_1_F",
	"U_C_Man_casual_2_F",
	"U_C_Man_casual_3_F",
	"U_C_Man_casual_4_F",
	"U_C_Man_casual_5_F",
	"U_C_Man_casual_6_F",
	"U_C_Mechanic_01_F",
	"U_C_Paramedic_01_F",
	"U_C_Poloshirt_blue",
	"U_C_Poloshirt_burgundy",
	"U_C_Poloshirt_redwhite",
	"U_C_Poloshirt_salmon",
	"U_C_Poloshirt_stripped",
	"U_C_Poloshirt_tricolour",
	"U_C_Poor_1",
	"U_C_Uniform_Farmer_01_F",
	"U_C_Uniform_Scientist_01_F",
	"U_C_Uniform_Scientist_01_formal_F",
	"U_C_Uniform_Scientist_02_F",
	"U_C_Uniform_Scientist_02_formal_F",
	"U_C_man_sport_1_F",
	"U_C_man_sport_2_F",
	"U_C_man_sport_3_F",
	"U_Competitor",
	"U_I_C_Soldier_Bandit_1_F",
	"U_I_C_Soldier_Bandit_2_F",
	"U_I_C_Soldier_Bandit_3_F",
	"U_I_C_Soldier_Bandit_4_F",
	"U_I_C_Soldier_Bandit_5_F",
	"U_I_L_Uniform_01_tshirt_black_F",
	"U_I_L_Uniform_01_tshirt_olive_F",
	"U_I_L_Uniform_01_tshirt_skull_F",
	"U_I_L_Uniform_01_tshirt_sport_F",
	"U_I_Wetsuit",
	"U_Marshal",
	"U_O_R_Gorka_01_black_F",
	"U_O_Wetsuit",
	"U_OrestesBody",
	"U_Rangemaster",

    // Vanilla Vests
    "V_BandollierB_blk",
	"V_BandollierB_cbr",
	"V_BandollierB_ghex_F",
	"V_BandollierB_khk",
	"V_BandollierB_oli",
	"V_BandollierB_rgr",
	"V_Chestrig_blk",
	"V_Chestrig_khk",
	"V_Chestrig_oli",
	"V_Chestrig_rgr",
	"V_HarnessOGL_brn",
	"V_HarnessOGL_gry",
	"V_HarnessO_brn",
	"V_HarnessO_gry",
	"V_I_G_resistanceLeader_F",
	"V_LegStrapBag_black_F",
	"V_LegStrapBag_coyote_F",
	"V_LegStrapBag_olive_F",
	"V_Pocketed_black_F",
	"V_Pocketed_coyote_F",
	"V_Pocketed_olive_F",
	"V_Rangemaster_belt",
	"V_RebreatherB",
	"V_SmershVest_01_F",
	"V_SmershVest_01_radio_F",
	"V_TacChestrig_cbr_F",
	"V_TacChestrig_grn_F",
	"V_TacChestrig_oli_F",
	"V_TacVest_blk",
	"V_TacVest_brn",
	"V_TacVest_camo",
	"V_TacVest_khk",
	"V_TacVest_oli",

    // Vanilla Glasses
    "G_AirPurifyingRespirator_01_F",
	"G_AirPurifyingRespirator_02_black_F",
	"G_AirPurifyingRespirator_02_olive_F",
	"G_AirPurifyingRespirator_02_sand_F",
	"G_Aviator",
	"G_B_Diving",
	"G_Balaclava_BlueStrips",
	"G_Balaclava_Flecktarn",
	"G_Balaclava_Skull1",
	"G_Balaclava_Tropentarn",
	"G_Balaclava_blk",
	"G_Balaclava_combat",
	"G_Balaclava_lowprofile",
	"G_Balaclava_oli",
	"G_Bandanna_BlueFlame2",
	"G_Bandanna_CandySkull",
	"G_Bandanna_OrangeFlame1",
	"G_Bandanna_Skull1",
	"G_Bandanna_Skull2",
	"G_Bandanna_Syndikat1",
	"G_Bandanna_Syndikat2",
	"G_Bandanna_aviator",
	"G_Bandanna_beast",
	"G_Bandanna_blk",
	"G_Bandanna_khk",
	"G_Bandanna_oli",
	"G_Bandanna_shades",
	"G_Bandanna_sport",
	"G_Bandanna_tan",
	"G_Combat",
	"G_Combat_Goggles_tna_F",
	"G_RegulatorMask_F",
	"G_Shades_Black",
	"G_Shades_Blue",
	"G_Shades_Green",
	"G_Shades_Red",
	"G_Spectacles",
	"G_Spectacles_Tinted",
	"G_Sport_BlackWhite",
	"G_Sport_Blackred",
	"G_Sport_Blackyellow",
	"G_Sport_Checkered",
	"G_Sport_Greenblack",
	"G_Sport_Red",
	"G_Squares",
	"G_Squares_Tinted",
	"G_Tactical_Black",
	"G_Tactical_Clear",
	"G_WirelessEarpiece_F",

    // Vanilla Binos
    "Binocular",
	"Laserdesignator",
	"Laserdesignator_01_khk_F",
	"Laserdesignator_03",

    // Vanilla Optics
    "optic_ACO_grn",
	"optic_ACO_grn_smg",
	"optic_Aco",
	"optic_Aco_smg",
	"optic_Arco",
	"optic_DMS",
	"optic_Hamr",
	"optic_Holosight",
	"optic_Holosight_smg",
	"optic_LRPS",
	"optic_MRCO",
	"optic_MRD",
	"optic_NVS",
	"optic_Nightstalker",
	"optic_SOS",
	"optic_Yorris",

    // Vanilla Items
    "B_UavTerminal",
	"C_UavTerminal",
	"ChemicalDetector_01_watch_F",
	"I_E_UavTerminal",
	"I_UavTerminal",
	"ItemCompass",
	"ItemWatch",
	"O_UavTerminal",
	"ToolKit",

    // ACE NVGs
    "ACE_NVG_Gen1",
	"ACE_NVG_Gen1_Brown",
	"ACE_NVG_Gen1_Green",
	"ACE_NVG_Gen2",
	"ACE_NVG_Gen2_Brown",
	"ACE_NVG_Gen2_Green",
	"ACE_NVG_Gen3",
	"ACE_NVG_Gen3_Brown",
	"ACE_NVG_Gen3_Green",
	"ACE_NVG_Gen4",
	"ACE_NVG_Gen4_Black_WP",
	"ACE_NVG_Gen4_Brown",
	"ACE_NVG_Gen4_Green",
	"ACE_NVG_Gen4_Green_WP",
	"ACE_NVG_Gen4_WP",
	"ACE_NVG_Wide",
	"ACE_NVG_Wide_Black",
	"ACE_NVG_Wide_Black_WP",
	"ACE_NVG_Wide_Green",
	"ACE_NVG_Wide_Green_WP",
	"ACE_NVG_Wide_WP",
	"ACE_NVGoggles_INDEP_WP",
	"ACE_NVGoggles_OPFOR_WP",
	"ACE_NVGoggles_WP",

    // ACE Binos
    "ACE_MX2A",
	"ACE_Vector",
	"ACE_VectorDay",
	"ACE_Yardage450",
	"ace_dragon_sight",

    // ACE Lights / Lasers
    "ACE_DBAL_A3_Green",
	"ACE_DBAL_A3_Red",
	"ACE_SPIR",
	"ACE_acc_pointer_green",

    // ACE Muzzle
    "ACE_muzzle_mzls_338",
	"ACE_muzzle_mzls_93mmg",
	"ACE_muzzle_mzls_B",
	"ACE_muzzle_mzls_H",
	"ACE_muzzle_mzls_L",
	"ACE_muzzle_mzls_smg_01",
	"ACE_muzzle_mzls_smg_02",

    // ACE Items
    "ACE_Altimeter",
    "ACE_RangeTable_82mm",
    "ACE_artilleryTable",
    "ACE_ATragMX",
    "ACE_Fortify",
    "ACE_DAGR",
    "ACE_wirecutter",
    "ACE_RangeCard",
    "ACE_DefusalKit",
    "ACE_Flashlight_MX991",
    "ACE_HuntIR_monitor",
    "ACE_MapTools",
    "ACE_Kestrel4500",
    "ACE_EntrenchingTool",
    "ACE_Chemlight_Shield",
    "ACE_Flashlight_KSF1",
    "ACE_M26_Clacker",
    "ACE_Clacker",
    "ACE_Flashlight_XL50",
    "ACE_microDAGR",
    "ACE_Cellphone",
    "ACE_PlottingBoard",
    "ACE_Tripod",
    "ACE_SpottingScope",
    "ACE_DeadManSwitch",
    "ACE_rope12",
    "ACE_rope15",
    "ACE_rope18",
    "ACE_rope27",
    "ACE_rope3",
    "ACE_rope36",
    "ACE_rope6",
    "ACE_SpareBarrel",
    "ACE_IR_Strobe_Item",
    "ACE_CableTie",
    "ace_marker_flags_blue",
    "ace_marker_flags_yellow",
    "ace_marker_flags_green",
    "ace_marker_flags_purple",
    "ace_marker_flags_orange",
    "ace_marker_flags_red",
    "ace_marker_flags_black",
    "ace_marker_flags_white",
    "ACE_EarPlugs",
    "ACE_Sandbag_empty",
    "ACE_SpraypaintBlue",
    "ACE_SpraypaintYellow",
    "ACE_SpraypaintGreen",
    "ACE_SpraypaintRed",
    "ACE_SpraypaintBlack",
    "ACE_SpraypaintWhite",
    "ACE_UAVBattery",

    // ACE Medical
    "ACE_adenosine",
    "ACE_fieldDressing",
    "ACE_elasticBandage",
    "ACE_packingBandage",
    "ACE_quikclot",
    "ACE_bloodIV",
    "ACE_bloodIV_250",
    "ACE_bloodIV_500",
    "ACE_epinephrine",
    "ACE_salineIV",
    "ACE_salineIV_250",
    "ACE_salineIV_500",
    "ACE_bodyBag_blue",
    "ACE_bodyBag",
    "ACE_bodyBag_white",
    "ACE_morphine",
    "ACE_suture",
    "ACE_surgicalKit",
    "ACE_personalAidKit",
    "ACE_plasmaIV",
    "ACE_plasmaIV_250",
    "ACE_plasmaIV_500",
    "ACE_splint",
    "ACE_painkillers",
    "ACE_tourniquet",

    // ACRE Items
    "ACRE_PRC117F",
    "ACRE_PRC148",
    "ACRE_PRC152",
    "ACRE_PRC343",
    "ACRE_PRC77",
    "ACRE_SEM52SL",
    "ACRE_SEM70",
    "ACRE_VHF30108",
    "ACRE_VHF30108MAST",
    "ACRE_VHF30108SPIKE",

    //TFAR Items
    "tf_anprc148jem",
    "tf_anprc152",
    "tf_anprc154_1",
    "tf_fadak",
    "tf_microdagr",
    "tf_pnr1000a_1",
    "tf_rf7800str"
];

GRLIB_arsenal_backpacks = [
    
    // Vanilla Standard Backpacks
    "B_AssaultPack_blk",
	"B_AssaultPack_khk",
	"B_AssaultPack_rgr",
	"B_AssaultPack_sgg",
	"B_Carryall_blk",
	"B_Carryall_cbr",
	"B_Carryall_khk",
	"B_Carryall_oli",
	"B_Carryall_oucamo",
	"B_FieldPack_blk",
	"B_FieldPack_cbr",
	"B_FieldPack_khk",
	"B_FieldPack_oli",
	"B_FieldPack_oucamo",
	"B_Kitbag_cbr",
	"B_Kitbag_rgr",
	"B_Kitbag_sgg",
	"B_Kitbag_tan",
	"B_Parachute",
	"B_TacticalPack_blk",
	"B_TacticalPack_oli",
	"B_TacticalPack_rgr",
	"B_AssaultPack_cbr",

    // ACE Backpacks
    "ACE_NonSteerableParachute",
	"ACE_TacticalLadder_Pack",
	"ace_gunbag",
	"ace_gunbag_Tan",

    // TFAR Backpacks
    "tf_anarc164",
    "tf_anarc210",
    "tf_anprc155_coyote",
    "tf_anprc155",
    "tf_bussole",
    "tf_mr3000_multicam",
    "tf_mr3000",
    "tf_mr6000l",
    "tf_rt1523g_big",
    "tf_rt1523g_black",
    "tf_rt1523g_fabric",
    "tf_rt1523g_green",
    "tf_rt1523g_sage",
    "tf_rt1523g"
];